### ISSUE TITLE
Dataset

### ISSUE THREAD

**Issue by shlomi-amitai** [team-ergo-unipi/ergo_uvo#1]
Hi, 

Can you share the dataset you were using?

**Comment by francescoruscio** [comment]
Hi, 

We will shortly release an updated version of the code and also include a dataset to test the algorithm.

**Comment by RiccardoCostanzi** [comment]
Hi @shlomi-amitai,

as previously anticipated, we have just released a new version of the code together with a bag file to test the Monocular Visual Odometry node.
Please feel free to report any issues or feedback.

**Comment by francescoruscio** [comment]
Hi @shlomi-amitai,

as previously anticipated, we have just released a new version of the code together with a bag file to test the Monocular Visual Odometry node.
Please feel free to report any issues or feedback.
